package com.drcmind.kelasisuite.domain.model.teacher

data class PreparationTemplate(
    val id: String,
    val name: String,
    val description: String,
    val category: String,
    val subBranch: String,
    val revisionSubject: String,
    val lessonSubject: String,
    val objective: String,
    val material: String,
    val bibliography: String,
    val introDuration: String = "5 min",
    val introMethod: String = "Interrogative / Rappel",
    val introContent: String,
    val devDuration: String = "30 min",
    val devMethod: String = "Expositive & Participative",
    val devContent: String,
    val synthDuration: String = "10 min",
    val synthMethod: String = "Active / Résumé au tableau",
    val synthContent: String,
    val appDuration: String = "5 min",
    val appMethod: String = "Exercices individuels",
    val appContent: String
)

val standardLessonTemplates = listOf(
    PreparationTemplate(
        id = "tpl_sciences",
        name = "Sciences & Mathématiques (Déductif)",
        description = "Structure standard avec rappel de formules, démonstration, exemples types et exercices d'application.",
        category = "Sciences Exactes",
        subBranch = "Algèbre / Physique",
        revisionSubject = "Rappel de la leçon précédente et correction du devoir",
        lessonSubject = "Propriétés et résolution des équations",
        objective = "À la fin de la leçon, l'élève sera capable de résoudre correctement au moins 3 équations sans aide.",
        material = "Tableau noir, craie blanche/couleur, calculatrice, compas",
        bibliography = "Manuel National de Mathématiques, Programme National RDC",
        introDuration = "5 min",
        introMethod = "Interrogation orale",
        introContent = "Contrôle des présences et des prérequis. Énoncé du problème introductif.",
        devDuration = "30 min",
        devMethod = "Exposé interactif et travail au tableau",
        devContent = "1. Définition des concepts clés.\n2. Démonstration de la propriété fondamentale.\n3. Résolution guidée d'un exemple type au tableau.",
        synthDuration = "10 min",
        synthMethod = "Participation des élèves",
        synthContent = "Élaboration conjointe du résumé et écriture des formules clés dans les cahiers.",
        appDuration = "5 min",
        appMethod = "Exercice écrit individuel",
        appContent = "Résoudre l'exercice 1 et 2 page 45 dans les cahiers d'exercices."
    ),
    PreparationTemplate(
        id = "tpl_lettres",
        name = "Français & Littérature (Texte & Grammaire)",
        description = "Idéal pour l'analyse de texte, la grammaire, la conjugaison et l'expression écrite.",
        category = "Langues & Lettres",
        subBranch = "Grammaire / Vocabulaire",
        revisionSubject = "Contrôle de la règle vue à la leçon précédente",
        lessonSubject = "L'accord du participe passé avec l'auxiliaire avoir",
        objective = "L'élève sera capable d'appliquer la règle d'accord du participe passé avec le COD placé avant le verbe dans 4 phrases sur 5.",
        material = "Texte support polycopié, tableau, dictionnaire",
        bibliography = "Grammaire Française de référence, Guide de l'enseignant",
        introDuration = "7 min",
        introMethod = "Lecture magistrale",
        introContent = "Lecture du texte modèle par le professeur puis par deux élèves.",
        devDuration = "28 min",
        devMethod = "Observation et découverte guidée",
        devContent = "1. Repérage des verbes et de leurs compléments d'objet direct.\n2. Formulation de l'hypothèse de la règle par les élèves.\n3. Validation institutionnelle de la règle par le professeur.",
        synthDuration = "10 min",
        synthMethod = "Schéma récapitulatif",
        synthContent = "Copie de la règle dans le cahier avec des phrases modèles surlignées.",
        appDuration = "5 min",
        appMethod = "Application immédiate",
        appContent = "Compléter et accorder les participes passés dans l'exercice d'entraînement."
    ),
    PreparationTemplate(
        id = "tpl_histoire_geo",
        name = "Sciences Humaines (Histoire / Géo / Éducation Civique)",
        description = "Approche documentaire avec étude de cartes, documents historiques et débats citoyens.",
        category = "Sciences Humaines",
        subBranch = "Histoire Contemporaine",
        revisionSubject = "Situation géopolitique vue au cours précédent",
        lessonSubject = "Les grands jalons historiques et leurs impacts sociétaux",
        objective = "L'élève sera capable de situer chronologiquement les événements majeurs et d'en expliquer les causes fondamentales.",
        material = "Carte murale, frise chronologique, documents d'archives",
        bibliography = "Atlas historique d'Afrique centrale, Manuel d'Histoire",
        introDuration = "5 min",
        introMethod = "Questionnement / Brainstorming",
        introContent = "Observation d'une image d'époque pour susciter la curiosité et amorcer le débat.",
        devDuration = "30 min",
        devMethod = "Analyse documentaire interactive",
        devContent = "1. Contexte socio-politique de l'époque.\n2. Déroulement des faits marquants.\n3. Conséquences économiques et humaines.",
        synthDuration = "10 min",
        synthMethod = "Frise chronologique",
        synthContent = "Mise en place de la frise chronologique et prise de notes des dates repères.",
        appDuration = "5 min",
        appMethod = "Questions orales de contrôle",
        appContent = "Répondre à deux questions d'évaluation formative pour vérifier l'assimilation."
    )
)
